import { Member, Application, StateChange, StatusChangeHistory } from './types';

// 초기 회원 데이터
export const initialMembers: Member[] = [
  // 관리자 전용 계정 (시스템 관리용, 정원 미포함, 회원 목록에 표시되지 않음)
  {
    id: 'admin',
    email: 'admin',
    password: 'zlsu2024!',
    name: '시스템관리자',
    phone: '',
    status: 'active',
    role: 'admin',
    joinedAt: '2023-01-01',
    updatedAt: '2024-01-01',
  },
  // 일반 회원 (정원 16명)
  {
    id: '1',
    email: 'hansunwoo@test.com',
    password: 'test123',
    name: '한선우',
    position: '수영 지도',
    phone: '010-1001-0001',
    gender: 'male',
    birthDate: '1985-03-15',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: true },
    swimmingLevel: 'masters',
    motivation: '수영 실력을 키우고 좋은 사람들과 함께 운동하고 싶습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    email: 'leeunyoung@test.com',
    password: 'test123',
    name: '이은영',
    phone: '010-1002-0002',
    gender: 'female',
    birthDate: '1965-07-20',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '건강 관리를 위해 꾸준히 수영하고 싶어요.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    email: 'choisunsuk@test.com',
    password: 'test123',
    name: '최선숙',
    position: '수모 담당',
    phone: '010-1003-0003',
    gender: 'female',
    birthDate: '1975-11-08',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    swimmingLevel: 'advanced',
    motivation: '수영 동호회에서 즐겁게 운동하고 싶습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '4',
    email: 'jungsangok@test.com',
    password: 'test123',
    name: '정상옥',
    phone: '010-1004-0004',
    gender: 'female',
    birthDate: '1973-02-22',
    birthDateType: 'lunar',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '규칙적인 운동 습관을 만들고 싶어요.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-02-15',
    updatedAt: '2024-02-15',
  },
  {
    id: '5',
    email: 'seomija@test.com',
    password: 'test123',
    name: '서미자',
    phone: '010-1005-0005',
    gender: 'female',
    birthDate: '1963-09-12',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '건강을 위해 수영을 시작하려고 합니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-03-01',
    updatedAt: '2024-03-01',
  },
  {
    id: '6',
    email: 'seobumsu@test.com',
    password: 'test123',
    name: '서범수',
    position: '대회 담당',
    phone: '010-1006-0006',
    gender: 'male',
    birthDate: '1983-06-30',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: true },
    swimmingLevel: 'masters',
    motivation: '수영 대회에 참가하고 싶어서 모임을 찾았습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-03-15',
    updatedAt: '2024-03-15',
  },
  {
    id: '7',
    email: 'leehyunwoo@test.com',
    password: 'test123',
    name: '이현우',
    position: '소통 담당',
    phone: '010-1007-0007',
    gender: 'male',
    birthDate: '1985-02-14',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: false, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '좋은 사람들과 함께 수영하고 싶습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-04-01',
    updatedAt: '2024-04-01',
  },
  {
    id: '8',
    email: 'leroro@inseq.co.kr',
    password: 'test123',
    name: '임미선',
    position: '총무 담당',
    phone: '010-1008-0008',
    gender: 'female',
    birthDate: '1982-08-05',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    swimmingLevel: 'advanced',
    motivation: '수영을 좋아하고 함께 운동할 동료를 찾고 있었어요!',
    status: 'active',
    role: 'member',
    joinedAt: '2023-04-15',
    updatedAt: '2024-04-15',
  },
  {
    id: '9',
    email: 'choibyungdon@test.com',
    password: 'test123',
    name: '최병돈',
    phone: '010-1009-0009',
    gender: 'male',
    birthDate: '1992-12-22',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '체력 단련과 스트레스 해소를 위해 수영을 하고 싶습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-05-01',
    updatedAt: '2024-05-01',
  },
  {
    id: '10',
    email: 'parkchan@test.com',
    password: 'test123',
    name: '박찬',
    phone: '010-1010-0010',
    gender: 'male',
    birthDate: '2002-05-18',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '수영을 더 잘하고 싶어서 가입합니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-05-15',
    updatedAt: '2024-05-15',
  },
  {
    id: '11',
    email: 'jangseokwon@test.com',
    password: 'test123',
    name: '장석원',
    phone: '010-1011-0011',
    gender: 'male',
    birthDate: '1995-10-03',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: false, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '수영 기초부터 배우고 싶습니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2023-06-01',
    updatedAt: '2024-06-01',
  },
  {
    id: '12',
    email: 'leejungbum@test.com',
    password: 'test123',
    name: '이정범',
    phone: '010-1012-0012',
    gender: 'male',
    birthDate: '1984-01-28',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    swimmingLevel: 'advanced',
    motivation: '주말마다 규칙적으로 수영하고 싶어요.',
    status: 'inactive',
    role: 'member',
    joinedAt: '2023-06-15',
    updatedAt: '2024-06-15',
  },
  {
    id: '13',
    email: 'ohhanna@test.com',
    password: 'test123',
    name: '오한나',
    phone: '010-1013-0013',
    gender: 'female',
    birthDate: '1985-07-11',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: false, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '수영 초보인데 배우고 싶어서 신청합니다.',
    status: 'active',
    role: 'member',
    joinedAt: '2026-01-10',  // 최근 가입
    updatedAt: '2026-01-10',
  },
  {
    id: '14',
    email: 'moonjungkyung@test.com',
    password: 'test123',
    name: '문정경',
    phone: '010-1014-0014',
    gender: 'female',
    birthDate: '1993-03-07',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '다이어트도 하고 수영 실력도 늘리고 싶어요!',
    status: 'active',
    role: 'member',
    joinedAt: '2026-01-17',  // 최근 가입
    updatedAt: '2026-01-17',
  },
  {
    id: '15',
    email: 'kangsoyeon@test.com',
    password: 'test123',
    name: '강소연',
    phone: '010-1015-0015',
    gender: 'female',
    birthDate: '1991-11-19',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: false, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '수영을 좋아해서 같이 운동할 모임을 찾았습니다.',
    status: 'inactive',
    role: 'member',
    joinedAt: '2025-06-01',
    updatedAt: '2026-01-14',  // 최근 휴면 전환
  },
  {
    id: '16',
    email: 'joyounghoon@test.com',
    password: 'test123',
    name: '조영훈',
    phone: '010-1016-0016',
    gender: 'male',
    birthDate: '1994-09-26',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '꾸준히 운동하는 습관을 만들고 싶습니다.',
    status: 'inactive',
    role: 'member',
    joinedAt: '2025-03-15',
    updatedAt: '2026-01-19',  // 최근 휴면 전환
  },
  // ============ 이중 승인 테스트 회원 ============

  // 테스트 케이스 1: 추천인 승인 대기 중
  {
    id: 'pending1',
    email: 'pending@test.com',
    password: 'test123',
    name: '김대기',
    phone: '010-9999-0001',
    gender: 'male',
    birthDate: '1995-05-15',
    referrer: '한선우',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '수영을 배우고 싶어서 가입 신청합니다.',
    status: 'pending',
    role: 'member',
    joinedAt: '2026-01-20',
    updatedAt: '2026-01-20',
    referrerApproval: { status: 'pending' },
  },

  // 테스트 케이스 2: 추천인 승인 완료, 관리자 승인 대기 중
  {
    id: 'pending2',
    email: 'pending2@test.com',
    password: 'test123',
    name: '이승인',
    phone: '010-9999-0002',
    gender: 'female',
    birthDate: '1998-08-20',
    referrer: '임미선',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: false, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '건강을 위해 수영을 시작하고 싶습니다.',
    status: 'pending',
    role: 'member',
    joinedAt: '2026-01-18',
    updatedAt: '2026-01-19',
    referrerApproval: {
      status: 'approved',
      processedAt: '2026-01-19',
      agreedToSuitability: true,
      agreedToMentoring: true,
    },
    adminApproval: { status: 'pending' },
  },

  // 테스트 케이스 3: 추천인에게 반려된 회원
  {
    id: 'pending3',
    email: 'pending3@test.com',
    password: 'test123',
    name: '박반려',
    phone: '010-9999-0003',
    gender: 'male',
    birthDate: '2000-03-10',
    referrer: '서범수',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    swimmingLevel: 'beginner',
    motivation: '수영 동호회 활동을 하고 싶습니다.',
    status: 'pending',
    role: 'member',
    joinedAt: '2026-01-17',
    updatedAt: '2026-01-18',
    referrerApproval: {
      status: 'rejected',
      processedAt: '2026-01-18',
      rejectReason: '직접 만나본 적이 없어서 추천하기 어렵습니다.',
    },
  },

  // 테스트 케이스 4: 임미선의 추천인 승인 대기 (임미선 계정 테스트용)
  {
    id: 'pending4',
    email: 'pending4@test.com',
    password: 'test123',
    name: '최신청',
    phone: '010-9999-0004',
    gender: 'female',
    birthDate: '1997-06-15',
    referrer: '임미선',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    swimmingLevel: 'intermediate',
    motivation: '임미선님 소개로 가입 신청합니다. 함께 수영하고 싶어요!',
    status: 'pending',
    role: 'member',
    joinedAt: '2026-01-21',
    updatedAt: '2026-01-21',
    referrerApproval: { status: 'pending' },
  },
];

// 초기 가입 신청 데이터
export const initialApplications: Application[] = [
  {
    id: '1',
    name: '신청자A',
    email: 'applicant1@test.com',
    password: 'test123',
    phone: '010-6666-7777',
    swimmingAbility: { freestyle: true, backstroke: false, breaststroke: true, butterfly: false },
    motivation: '수영을 배우고 싶어서 가입 신청합니다.',
    agreedToTerms: true,
    agreedToPrivacy: true,
    status: 'pending',
    createdAt: '2026-01-19',
  },
  {
    id: '2',
    name: '신청자B',
    email: 'applicant2@test.com',
    password: 'test123',
    phone: '010-7777-8888',
    birthDate: '2000-03-25',
    referrer: '김철수',
    swimmingAbility: { freestyle: true, backstroke: true, breaststroke: true, butterfly: false },
    motivation: '건강을 위해 수영 모임에 참여하고 싶습니다.',
    agreedToTerms: true,
    agreedToPrivacy: true,
    status: 'pending',
    createdAt: '2026-01-20',
  },
];

// 초기 상태 변경 신청 데이터
export const initialStateChanges: StateChange[] = [
  {
    id: '1',
    memberId: '12',
    memberName: '이정범',
    currentStatus: 'inactive',
    requestedStatus: 'active',
    reason: '다시 활동을 시작하고 싶습니다.',
    status: 'pending',
    createdAt: '2026-01-18',
  },
];

// 초기 상태 변경 이력 데이터 (대시보드 표시용)
export const initialStatusChangeHistory: StatusChangeHistory[] = [
  {
    id: 'h1',
    memberId: '13',
    memberName: '오한나',
    changeType: 'joined',
    toStatus: 'active',
    changedAt: '2026-01-10T10:00:00',
  },
  {
    id: 'h2',
    memberId: '15',
    memberName: '강소연',
    changeType: 'to_inactive',
    fromStatus: 'active',
    toStatus: 'inactive',
    changedAt: '2026-01-14T14:30:00',
  },
  {
    id: 'h3',
    memberId: '14',
    memberName: '문정경',
    changeType: 'joined',
    toStatus: 'active',
    changedAt: '2026-01-17T09:00:00',
  },
  {
    id: 'h4',
    memberId: '16',
    memberName: '조영훈',
    changeType: 'to_inactive',
    fromStatus: 'active',
    toStatus: 'inactive',
    changedAt: '2026-01-19T11:00:00',
  },
];
